parameters:
#    fa_fa_time_mb_app.example.class: Justsy\AdminAppBundle\Example

services:
#    fa_fa_time_mb_app.example:
#        class: %fa_fa_time_mb_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
