parameters:
#    fa_fa_web_im_im_main.example.class: WebIM\ImMainBundle\Example

services:
#    fa_fa_web_im_im_main.example:
#        class: %fa_fa_web_im_im_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
