parameters:
#    fa_fa_time_we_interface.example.class: Justsy\InterfaceBundle\Example

services:
#    fa_fa_time_we_interface.example:
#        class: %fa_fa_time_we_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
