parameters:
#    fa_fa_web_im_im_ocs_manager.example.class: WebIM\ImOCSManagerBundle\Example

services:
#    fa_fa_web_im_im_ocs_manager.example:
#        class: %fa_fa_web_im_im_ocs_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
