imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        storage_id: session.storage.pdo

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals: 
        FILE_WEBSERVER_URL: %FILE_WEBSERVER_URL% 
        ISDEBUG: %kernel.debug%
        IM_SERVER: %ejabberd-server-http%
        JS_OPEN_API_URL: %open_api_url%
        WEBIM_URL: %fafa_webim_url%
        APPCENTER_URL: %fafa_appcenter_url%
        USER_AUTH_METHD: %ssoauthmodule%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            im:
                driver:   %database_driver_im%
                host:     %database_host_im%
                port:     %database_port_im%
                dbname:   %database_name_im%
                user:     %database_user_im%
                password: %database_password_im%
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options:
                connect: true
                username: %mongodb_username%
                password: %mongodb_password%
    default_database: %mongodb_default_database%
    document_managers:
        default:
            auto_mapping: true
            
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: login

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

parameters:
  pdo.db_options:
    db_table: session
    db_id_col: session_id
    db_data_col: session_value
    db_time_col: session_time

services:
  pdo:
    class: PDO
    arguments:
      dsn: "mysql:host=%database_host%;dbname=%database_name%;port=%database_port%"
      user: %database_user%
      password: %database_password%
  session.storage.pdo:
    class: Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
    arguments: [@pdo, %session.storage.options%, %pdo.db_options%]