OpenAPIBundle:
    resource: "@JustsyOpenAPIBundle/Resources/config/routing.yml"
    prefix:   /

JustsyInterfaceBundle:
    resource: "@JustsyInterfaceBundle/Resources/config/routing.yml"
    prefix:   /

root:
  pattern: /
#  defaults: {_controller: FrameworkBundle:Redirect:urlRedirect, path:/home, permanent: true}
  defaults: { _controller: JustsyBaseBundle:EnterpriseHome:home, name:foo}
  

JustsyMongoDocBundle:
    resource: "@JustsyMongoDocBundle/Resources/config/routing.yml"
    prefix:   /

JustsyBaseBundle:
    resource: "@JustsyBaseBundle/Resources/config/routing.yml"
    prefix:   /

JustsyAdminAppBundle:
    resource: "@JustsyAdminAppBundle/Resources/config/routing.yml"
    prefix:   /
WebIMImChatBundle:
    resource: "@WebIMImChatBundle/Resources/config/routing.yml"
    prefix:   /
WebIMImMainBundle:
    resource: "@WebIMImMainBundle/Resources/config/routing.yml"
    prefix:   /
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
